import {test} from 'node:test';import assert from 'node:assert/strict';import {run,apply,routes} from './routes';import {initialState,reduce,serialize,deserialize,npcStates,visibleHotspots,advance} from '../src/simulation/game';import {epilogue} from '../src/simulation/puzzles';
for(const name of Object.keys(routes))test(`${name} route rings the Moon Bell without state injection`,()=>{const s=run(name);assert.equal(s.finished,true,JSON.stringify({location:s.location,time:s.minute,message:s.message,flags:s.flags}));assert.ok(s.inventory.includes('sun'));assert.equal(s.flags['bell-rung'],true);assert.ok(s.events.every((e,i,all)=>i===0||e.at>=all[i-1].at),'chronological event log');if(name==='Helpful'){assert.equal(s.values['mill-solution'],'repair');assert.equal(s.values['bridge-solution'],'bell');assert.ok(s.minute<1260);}if(name==='Expedient'){assert.equal(s.values['bridge-solution'],'key');assert.equal(s.memories.brindle.includes('saw-key-with-mara'),false);assert.ok(s.memories.ysabet.includes('lantern-missing'));assert.equal(s.memories.ysabet.includes('saw-lantern-with-mara'),false);}if(name==='Late')assert.equal(s.values['tower-route'],'courier postern');if(name==='Minimal')assert.equal(s.values['bridge-solution'],'ledge');});
test('save boundaries preserve phases, NPC routines, ownership and key',()=>{for(const minute of [1049,1050,1079,1080,1109,1110,1154,1155,1259,1260,1295]){let s=initialState();s.minute=minute;s.location='cottage';s=deserialize(serialize(s));assert.equal(s.minute,minute);assert.equal(npcStates(s).ysabet,minute>=1050&&minute<1080?'gathering':'home');s=reduce(s,{type:'wait',minutes:1});assert.equal(s.minute,minute+1);assert.ok(s.inventory.includes('sun'));assert.deepEqual(deserialize(serialize(s)),s);}});
test('returned lantern and plausible knowledge survive reload',()=>{let s=initialState();for(const step of routes.Helpful){s=apply(s,step);if(s.inventory.includes('lantern'))break;}while(s.minute<1080)s=reduce(s,{type:'wait',minutes:Math.min(30,1080-s.minute)});s=reduce(s,{type:'interact',id:'ysabet',verb:'Use',item:'lantern'});s=deserialize(serialize(s));assert.equal(s.itemLocations.lantern,'cottage');assert.equal(s.provenance.lantern.returned,true);assert.ok(s.memories.ysabet.includes('lantern-returned'));});
test('reasonable wrong uses and unstable bridge are recoverable',()=>{let s=initialState();s=reduce(s,{type:'travel',to:'mill'});s=reduce(s,{type:'interact',id:'beam',verb:'Place'});s=reduce(s,{type:'interact',id:'span',verb:'Walk'});assert.equal(s.location,'mill');assert.match(s.message,/loose beam/);s=reduce(s,{type:'interact',id:'wheel',verb:'Use',item:'sun'});assert.ok(s.inventory.includes('sun'));assert.match(s.message,/no courier/);});
test('missing starters have physical hen and reflector alternatives',()=>{let s=initialState();s.location='chapel';for(const [id,verb] of [['stones-hen','Place'],['mallow','Approach'],['disc','Take'],['disc','Take']])s=reduce(s,{type:'interact',id,verb});assert.ok(s.inventory.includes('hen'));assert.ok(s.inventory.includes('disc'));});
test('22:00 blocks new long work and exposes an explicit relief handover',()=>{let s=initialState();s.minute=1319;s=reduce(s,{type:'wait',minutes:5});assert.equal(s.minute,1324);const later=reduce(s,{type:'wait',minutes:15});assert.equal(later.minute,1324);assert.ok(visibleHotspots(later).some(h=>h.id==='courier'));s=reduce(later,{type:'interact',id:'courier',verb:'Entrust key'});assert.ok(s.finished);assert.ok(s.inventory.includes('sun'));assert.ok(s.minute>1324);});
test('long action processes every boundary exactly once',()=>{let s=initialState();advance(s,350);const ids=s.events.filter(e=>e.action==='boundary').map(e=>e.target);assert.equal(new Set(ids).size,ids.length);assert.ok(ids.includes('1050')&&ids.includes('1260'));});
test('epilogue uses recorded chronology and no omniscient accusations',()=>{const s=run('Expedient');assert.match(epilogue(s).join(' '),/does not know who/);assert.match(epilogue(s).join(' '),/which traveler/);});
