import {locations,type Hotspot} from '../content/world';
import {type State,npcStates,give,remember,clue,record,advance} from './game';
const has=(s:State,i:string)=>s.inventory.includes(i);
const remove=(s:State,i:string,where:string)=>{s.inventory=s.inventory.filter(x=>x!==i);s.itemLocations[i]=where;};
const set=(s:State,k:string)=>{s.flags[k]=true;};
function arrive(s:State,to:State['location'],route:string,cost=8){s.location=to;s.player={x:470,y:530};s.values[`${to}-route`]=route;advance(s,cost);}
export function puzzleFor(s:State){return s.location==='mill'?'P1':s.location==='crossroads'?'P2':['cottage','chapel','hollow'].includes(s.location)?'P3':s.location==='moonwell'?'P4':s.location==='bridge'?'P5':'P6';}
export function hintFor(s:State){const p=puzzleFor(s);const level=Math.min(3,(s.hints[p]||0)+1);s.hints[p]=level;const hints:Record<string,string[]>={P1:['The crossing and the mill share the same water.','Notice the jammed wheel, the capstan line, and the marks beside the sluice.','Try freeing the wheel and drawing its line; or turn the sluice to divert the river. The ferry sign offers another time.'],P2:['The road has changed, but something here has not.','The old oak and courier stone stay put when the signs turn.','Mark the oak, try a path, then compare the signs. Choose a route relative to the oak, not their arrows.'],P3:['The Hollow seems to conceal edges, rather than block the road.','Ysabet’s lantern sharpens edges. The hen’s feathers lead to the chapel.','Try returning Mallow to Ysabet. A blue bottle can also catch the lights that gather at dusk.'],P4:['These flowers are waiting for a different sky.','The chapel mural depicts the well, a reflective disc, and three ring directions.','After seven, place a mirror in the socket. Turn the rings until crescent points up, half right, full down.'],P5:['There is more than one level to this bridge.','A key rests by the sleeping keeper. The small toll bell is strangled by living thorn.','Try Moonwater on the thorn-bound bell; or shine True-Path light on the marked ravine wall.'],P6:['The Sun Key was made for an older road than the main gate.','The chapel mural shows a courier door. In the tower, the yoke and release are separate mechanisms.','Inspect the ivy for a courier lock after nine. Unlock the yoke; clear living thorn or expose the old catch, then pull the rope.']};return hints[p][level-1];}
export function play(s:State,h:Hotspot,verb:string,item?:string):{message:string;cost:number}{
let message=h.description,cost=1;
const use=verb==='Use';
if(item&&!has(s,item))return {message:'That object is no longer in your satchel.',cost:0};
if(s.minute>=1320){if(h.id==='courier'&&verb==='Entrust key'){finish(s,true);return {message:s.message,cost:1};}return {message:'The last runner waits beside you. There is no time for another long task; entrust the Sun Key to the relief courier.',cost:0};}
if(verb==='Look'){
 if(h.id==='gauge'){set(s,'gauge');clue(s,'At the mill, the spill notch diverts water away from the crossing.');}
 if(h.id==='door'){clue(s,'Ysabet gathers dusk-thyme from half past five until six.');}
 if(h.id==='stone'){set(s,'stone');clue(s,'The courier carving puts the road to the RIGHT of the boundary oak.');}
 if(h.id==='sign'&&s.flags.marked&&(s.values.loops as number||0)>0){set(s,'signs-moved');message='Your mark remains on the oak. The sign arms now face a different way. Only the old boundary stayed true.';clue(s,'The signs move; the marked boundary oak does not.');}
 if(h.id==='mural'){set(s,'mural');set(s,'courier-clue');message=h.description;clue(s,'Chapel mural: crescent UP, half RIGHT, full DOWN; a polished disc sends moonlight into the well.');clue(s,'An old courier door lies beneath Castle Arden’s left wall.');}
 if(h.id==='vines'&&(s.flags['courier-clue']||s.minute>=1260)){set(s,'postern');message='Tracing the old mortar, you find a low arch beneath the ivy. The lock bears a sunburst. The door is old enough to remember the Briar Road.';clue(s,'A sunburst courier lock is hidden beneath the castle ivy.');}
 if(h.id==='catch'&&s.minute>=1260&&!s.flags['catch-revealed']){set(s,'catch-revealed');cost=5;message='Mara traces the bronze pin by touch. Behind the briar is a small release catch, the same kind her master taught her to repair.';}
 if(h.id==='socket')message='The socket accepts a reflective surface. Its beam must pass through three four-way channels; little arrows on the rim show their directions.';
 return {message,cost};
}
if(use){
 if(item==='sun'&&h.id==='main-gate'){
 if(s.minute>=1260)message='The gate is barred. The key belongs to an older courier lock, not this new iron latch.';
 else{set(s,'key-shown');remember(s,'sella','saw-sun-key');message=s.flags['errand-told']?'Sella sees the Sun Key and steps aside. “Then go. The tower stair is yours.”':'Sella studies the sunburst. “Aldus’s key. Tell me why he has sent an apprentice in his place.”';if(s.flags['errand-told']){s.values.arrival=s.minute;arrive(s,'tower','main gate',4);}}return {message,cost:2};}
 if(item==='sun'&&h.id==='sella')return play(s,locations.castle.hotspots.find(x=>x.id==='main-gate')!,'Use','sun');
 if(item==='sun'&&h.id==='postern'){set(s,'postern-open');s.values.arrival=s.minute;message='The ancient lock recognizes its sun. Stone slides against stone, and the courier stair opens into the Moon Bell Tower.';arrive(s,'tower','courier postern',5);return {message,cost:2};}
 if(item==='sun'&&h.id==='yoke'){set(s,'yoke');message='The Sun Key turns. The locked yoke lifts a finger’s width; the release catch still holds the pin.';return {message,cost:2};}
 if(item==='sun')return {message:'The Sun Key remains in Mara’s hand. This object bears no courier sunburst lock.',cost:1};
 if(item==='thread'&&h.id==='oak'){set(s,'marked');message='You tie a red thread around the old oak. The marker is fixed to wood, not to a sign.';return {message,cost:2};}
 if(item==='cake'&&h.id==='mallow'){remove(s,'cake','consumed');give(s,'hen','chapel');set(s,'hen-found');message='Mallow follows the crumbs straight into your arms. She settles beneath your cloak with a silver-feathered grumble.';return {message,cost:3};}
 if(item==='hen'&&h.id==='ysabet'){remove(s,'hen','coop');set(s,'hen-returned');set(s,'permission');remember(s,'ysabet','mara-returned-mallow');remember(s,'ysabet','lent-lantern');message='Ysabet settles Mallow in her coop. “Borrow my lantern. Return it when your road is done; a borrowed light is still someone’s light.”';return {message,cost:3};}
 if(item==='lantern'&&h.id==='ysabet'){remove(s,'lantern','cottage');s.provenance.lantern.returned=true;remember(s,'ysabet','lantern-returned');message=s.flags.permission?'“A promise kept,” says Ysabet. “Mind the moon-road.”':'Ysabet sees her lantern in your hands. “So that is where it walked. Next time, knock.”';remember(s,'ysabet','saw-lantern-with-mara');return {message,cost:2};}
 if(item==='lantern'&&h.id==='edge'||item==='glowjar'&&h.id==='edge'){set(s,'hollow-lit');s.values.light=item;message=item==='lantern'?'The lantern draws a clean seam through the glamour. A real path lies beside the false one.':'The fireflies hover above firm ground. Their faint light reveals just enough of the folded path.';return {message,cost:1};}
 if(item==='lantern'&&h.id==='ledge'){set(s,'ledge');message='The lantern uncovers a pilgrim ledge cut beneath the bridge. The wall has been a path all along.';return {message,cost:2};}
 if(item==='lantern'&&h.id==='vines'){set(s,'postern');message='In the lantern light, a courier arch appears through the ivy. Its keyhole shines with a tiny sunburst.';return {message,cost:1};}
 if(item==='lantern'&&h.id==='catch'){set(s,'catch-revealed');set(s,'briar-cleared');message='True-Path light reveals a narrow safe reach through the binding thorn. Mara can work the old catch without touching its false barbs.';return {message,cost:2};}
 if(item==='bottle'&&h.id==='fireflies'&&s.minute>=1110){remove(s,'bottle','glowjar');give(s,'glowjar','garden fireflies');message='You cup a few fireflies into the blue bottle. Their light follows the true ground instead of the shifting shadows.';return {message,cost:3};}
 if(['mirror','disc'].includes(item||'')&&h.id==='socket'){set(s,'reflector');s.values.reflector=item!;remove(s,item!,'moonwell socket');message='The polished surface fits the socket. A thin beam now strikes the first ring.';return {message,cost:1};}
 if(['mirror','thread','cake'].includes(item||'')&&h.id==='pip'){remove(s,item!,'magpie nest');give(s,'disc','Pip trade');set(s,'disc-taken');message='Pip examines your offering and pushes the broad moon-disc out of the nest. A trade, by magpie standards.';return {message,cost:2};}
 if(item==='water'&&h.id==='toll-bell'){set(s,'toll-free');set(s,'woke');set(s,'gate');s.values['bridge-solution']='bell';remember(s,'brindle','saw-mara-free-bell');give(s,'charm','Brindle');message='Moonwater runs across the thorns. They uncurl. The little bell rings, and Brindle rises. “My bridge has a voice again. Take this, road-mender.”';return {message,cost:5};}
 if(['water','charm'].includes(item||'')&&h.id==='briars'){set(s,'briar-cleared');message=item==='water'?'A few drops loosen the living briar from the release mechanism. The vial still holds enough for the road.':'Brindle’s charm hums. The old briar settles around the stone instead of binding the mechanism.';return {message,cost:3};}
 if(item==='rope'&&h.id==='rope'){set(s,'rope-repaired');message='You knot Bram’s sound line onto the damaged pull. The old miller’s help reaches all the way to the tower.';return {message,cost:4};}
 if(item==='key'&&h.id==='gate'){set(s,'gate');s.values['bridge-solution']='key';if(npcStates(s).brindle==='awake'){remember(s,'brindle','saw-key-with-mara');message='Brindle watches his key turn in the lock. “That is mine, little traveler. Use it, then hang it back.”';}else message='The brass key turns quietly in the gate. Brindle’s snore covers the click.';return {message,cost:1};}
 if(item==='key'&&h.id==='brindle'){remember(s,'brindle','saw-key-with-mara');remove(s,'key','bridge nest');set(s,'gate');remember(s,'brindle','key-returned');message='You put the key into Brindle’s palm. He opens the gate himself. “Borrowing is a word better said before than after.”';return {message,cost:3};}
 if(item==='cake'&&h.id==='bram'){remove(s,'cake','consumed');remember(s,'bram','shared-cake');message='“Honey! Better than river mud,” says Bram, taking a small bite.';return {message,cost:2};}
 const feedback:Record<string,string>={thread:'The thread is too fine to bear weight, but could leave a mark on something fixed.',mirror:'The mirror catches a little sky. There is no beam or reflective socket here.',bottle:'The bottle needs something that can be caught or poured.',water:'A careful drop glistens and falls away. Only living briar or moon-stone responds to Moonwater.',lantern:'The lantern sharpens ordinary edges here. It reveals glamour; it does not open locks.',glowjar:'The lights hover toward solid ground. This faint light is useful for paths, not locks or machinery.',cake:'It smells sweet, but this object has no appetite.',disc:'The polished disc reflects the sky. It needs a place where the beam can be aimed.',charm:'The charm is quiet. There is no restless old briar here.',rope:'The sound line needs a loose or broken pull to secure.'};return {message:feedback[item||'']||'Mara holds the object beside it; the shapes do not fit. Try looking at the mechanism’s edges.',cost:1};
}
if(h.id==='aldus'&&verb==='Talk'){message='“The Sun Key releases the Moon Bell’s yoke. Before nine, Mara. The courier stone remembers the Briar Road.”';clue(s,'The Sun Key releases the Moon Bell yoke. The deadline is the ninth evening bell.');cost=3;}
else if(['thread','mirror','bottle','cake'].includes(h.id)&&verb==='Take'){give(s,h.id,'workshop','owned');message=`You tuck the ${h.name.toLowerCase()} into your satchel.`;cost=2;}
else if(h.id==='bram'&&verb==='Talk'){message=s.flags.wheel?'“Wheel’s running! Draw the line from that capstan, then lash a beam across. You’ll have earned a dry road.”':'“Branch in the paddles. The wheel drives the rope drum. And mind the sluice: spill runs away from the crossing, flood runs straight at it.”';clue(s,'The wheel drives the rope capstan. Bram says the spill channel runs away from the crossing.');cost=3;}
else if(h.id==='wheel'&&verb==='Pull'){if(s.flags.wheel)message='The wheel turns freely; there is no branch left to pull.';else{set(s,'wheel');remember(s,'bram','saw-mara-help-wheel');message='Together you and Bram heave the storm branch free. Water takes the wheel; the capstan creaks awake.';cost=15;}}
else if(h.id==='capstan'&&verb==='Pull'){if(!s.flags.wheel)message='The drum will not turn while the millwheel is jammed.';else{set(s,'line');give(s,'rope','Bram');message='You draw out the bridge line. Bram cuts off a spare length for your satchel. “Good rope remembers a good knot.”';cost=3;}}
else if(h.id==='beam'&&verb==='Place'){set(s,'beam');message=s.flags.line?'The beam spans the gap; the drawn line lies beside it, ready to lash.':'The beam spans the gap, but slides alarmingly. It needs the capstan line.';cost=8;}
else if(h.id==='beam'&&verb==='Secure'){if(s.flags.beam&&s.flags.line){set(s,'secured');s.values['mill-solution']='repair';remember(s,'bram','saw-mara-repair-span');message='You lash the beam to the bridge piles. The span holds its weight. Bram gives it one firm nod.';cost=5;}else message='There must be a beam and a released line before you can lash the span.';}
else if(h.id==='sluice'&&verb==='Turn'){const v=((s.values.sluice as number||0)+1)%3;s.values.sluice=v;cost=3;if(v===2){s.values['stones-until']=s.minute+15;message='The spill channel roars. Water falls below the carved mark, uncovering a line of stepping stones for a short time.';}else message=v===1?'The flood notch sends water surging toward the bridge. Bram shouts a warning. The lever can still be moved.':'The lever settles at the grain mark; river stones disappear beneath normal flow.';}
else if(h.id==='span'&&verb==='Walk'){if(!s.flags.secured)message='The gap is too wide. The loose beam would slide into the river.';else{arrive(s,'crossroads','repaired span');message='The repaired beam holds. Behind you, the millwheel turns again.';cost=0;}}
else if(h.id==='stones'&&verb==='Walk'){if(s.values.sluice!==2||s.minute>Number(s.values['stones-until']))message='The stones are under the current. The sluice would need to divert the flow again.';else{s.values['mill-solution']='sluice';arrive(s,'crossroads','stepping stones',6);message='You cross the wet stones before the spill channel fills again.';cost=0;}}
else if(h.id==='ferry'&&verb==='Board'){if(s.minute<1110)message='The ferry is tied on the far bank. Service begins when the fireflies light.';else{s.values['mill-solution']='ferry';arrive(s,'crossroads','dusk ferry',12);message='The ferryman carries you across the silver river. Behind the mill, the first lamps are lit.';cost=0;}}
else if(h.id==='oak'&&verb==='Mark'){set(s,'marked');message=has(s,'thread')?'You knot a red thread around the oak’s courier scar.':'You rub a pale chalk-stone into the oak’s courier scar. It leaves a clear fixed mark.';cost=2;}
else if(['left-path','right-path'].includes(h.id)&&verb==='Walk'){
if(h.id==='right-path'&&s.flags['signs-moved']&&s.flags.stone||h.id==='right-path'&&has(s,'lantern')){set(s,'crossroads-solved');s.values['crossroads-solution']='boundary';arrive(s,'hollow','boundary oak');message='Following the road relative to the ancient oak, you leave the turning signs behind. The old courier stone had kept its promise.';cost=0;}
else{s.values.loops=Number(s.values.loops||0)+1;advance(s,8);message='The road folds back to the clearing. The sign arms have turned; the oak’s scar has not moved.';if(s.flags.marked){set(s,'signs-moved');clue(s,'The marked boundary oak stays fixed while the signs turn.');}cost=0;}}
else if(h.id==='moths'&&verb==='Follow'){set(s,'crossroads-solved');s.values['crossroads-solution']='moths';arrive(s,'hollow','moonmoths',12);message='The moths ignore the signs and drift along a true edge of the wood.';cost=0;}
else if(h.id==='ysabet'&&verb==='Talk'){
 if(s.flags['hen-returned']&&s.minute>=1110&&!has(s,'water')){give(s,'water','Ysabet vial');s.values['water-source']='Ysabet';message='“Night has woken the old briar,” says Ysabet. “You brought Mallow home; take this Moonwater for the road.”';}
 else if(s.memories.ysabet.includes('saw-lantern-with-mara')&&!s.flags.permission)message='Ysabet looks at the lantern in your hand. “My tools are not communal property. Bring it back when the bell has rung.”';
 else if(s.flags.permission)message='“My lantern is yours to borrow. It reveals concealed edges. Moonwater loosens living thorn; those are different gifts.”';
 else message='“The Hollow’s edges lie,” says Ysabet. “My lantern sees through them, but I need it tonight. Bring Mallow home from the chapel, and I can spare it.”';set(s,'hen-task');clue(s,'Mallow fled to the chapel. Ysabet needs her hen home before lending the True-Path Lantern.');cost=3;}
else if(h.id==='door'&&verb==='Open'){set(s,'door-open');message='The ordinary latch lifts. A copper lantern hangs just inside.';cost=1;}
else if(h.id==='lantern'&&verb==='Take'){
 if(s.flags.permission){give(s,'lantern','Ysabet','lent','Ysabet');message='You lift the lantern from its hook, with Ysabet’s leave.';}
 else if(npcStates(s).ysabet==='gathering'&&s.flags['door-open']){give(s,'lantern','Ysabet hook','unasked','Ysabet');set(s,'lantern-taken');message='You lift the copper lantern from its hook. The cottage is quiet; Ysabet’s basket is gone.';}
 else message='Ysabet lays a hand on the lantern hook. “Ask first, traveler.”';cost=2;}
else if(h.id==='stones-hen'&&verb==='Place'){set(s,'hen-cornered');message='You shift a fallen stone across the narrow gap. Mallow’s next escape route leads into the open alcove.';cost=3;}
else if(h.id==='mallow'&&verb==='Approach'){if(s.flags['hen-cornered']){give(s,'hen','chapel');set(s,'hen-found');message='With the gap closed, you gently gather Mallow from the alcove. She objects, but no feathers are harmed.';}else{s.values['hen-position']=(Number(s.values['hen-position']||0)+1)%3;message='Mallow dodges through the gap between the fallen stones. Her next escape route is plain to see.';}cost=2;}
else if(h.id==='pip'&&verb==='Talk'){message='Pip turns one bright eye toward your satchel, then taps the polished disc. His understanding of trade is admirably direct.';}
else if(h.id==='disc'&&verb==='Take'){if(!s.flags['pip-distracted']){set(s,'pip-distracted');message='Pip flutters at your hand. A loose twig rattles down to the far side of the arch; he tilts his head toward it.';}else{give(s,'disc','abandoned courier nest');set(s,'disc-taken');message='While Pip inspects the fallen twig, you lift the moon-disc. The magpie has already found a shinier nail.';}cost=2;}
else if(h.id==='hollow-path'&&verb==='Walk'){if(!s.flags['hollow-lit']){message='The path returns you to its own beginning. The fireflies keep to firmer ground than the shadows.';cost=6;}else{arrive(s,'moonwell',String(s.values.light));message='True ground carries you through the last folding path. The whispers fall behind, and the Moonwell opens before you.';cost=0;}}
else if(h.id.startsWith('ring-')&&verb==='Turn'){const id=Number(h.id.slice(-1));s.values[`ring${id}`]=(Number(s.values[`ring${id}`]||0)+1)%4;const dir=['up','right','down','left'][Number(s.values[`ring${id}`])];message=`The ${['crescent','half-moon','full-moon'][id]} channel now points ${dir}. `+(s.flags.reflector&&s.minute>=1140?'The beam follows the carved channel.':'No moonbeam reaches the channel yet.');cost=1;}
else if(h.id==='socket'&&verb==='Take reflector'){if(s.flags.reflector){give(s,String(s.values.reflector),'moonwell socket','owned');s.flags.reflector=false;message='You lift the reflector out. The beam breaks at the empty socket.';}else message='The socket is empty.';}
else if(h.id==='basin'&&verb==='Fill'){
 if(s.minute<1140)message='No moonbeam reaches the glade yet. The closed flowers and cold stone wait for evening.';
 else if(!s.flags.reflector||Number(s.values.ring0||0)!==0||Number(s.values.ring1||0)!==1||Number(s.values.ring2||0)!==2)message='The basin is dry. The beam is missing a channel; each ring has a small directional arrow. The chapel mural showed their alignment.';
 else{give(s,'water','Moonwell stone cup');s.values['water-source']='Moonwell';set(s,'well-awake');message='Moonlight falls into the basin and ripples like water. You scoop a few drops into the little stone vial on its rim.';cost=1;}}
else if(h.id==='brindle'&&verb==='Talk'){if(npcStates(s).brindle==='asleep')message='Brindle answers with a snore that shakes the moss. A small toll bell hangs above his nest.';else{remember(s,'brindle','met-mara');message=s.flags['toll-free']?'“Go, road-mender. A working bell is a bridge’s heart.”':s.memories.brindle.includes('saw-key-with-mara')?'“That key in your hand belongs beside my nest. Put it back when you cross.”':'“No toll in years,” says Brindle. “Thorn took my bell. It is a poor bridge that cannot greet its travelers.”';}cost=3;}
else if(h.id==='bridge-key'&&verb==='Take'){if(npcStates(s).brindle==='awake')message='Brindle closes his enormous hand around the key. “Speak to the keeper while he is keeping.”';else{give(s,'key','Brindle nest','unasked','Brindle');set(s,'key-taken');message='You lift the brass key between two immense snores. Brindle has not seen you.';}cost=2;}
else if(h.id==='toll-bell'&&verb==='Ring'){set(s,'woke');message=s.flags['toll-free']?'The little bell sings over the ravine.':'The thorn muffles the bell. Brindle stirs at the dull knock, now awake.';cost=1;}
else if(h.id==='gate'&&verb==='Open'){message=s.flags.gate?'The bridge gate swings open.':'The brass lock holds. This is Brindle’s gate, not an ancient courier lock.';}
else if(h.id==='cross-bridge'&&verb==='Walk'){if(!s.flags.gate&&!s.flags.ledge)message='The gate holds the crossing. Beneath the arch, ivy conceals the ravine wall.';else{if(s.flags.ledge&&!s.flags.gate)s.values['bridge-solution']='ledge';arrive(s,'castle',String(s.values['bridge-solution']));message='Beyond the ravine, Castle Arden rises above the wood. The Moon Bell waits on the highest tower.';cost=0;}}
else if(h.id==='ledge'&&verb==='Walk'){if(s.flags.ledge){s.values['bridge-solution']='ledge';arrive(s,'castle','pilgrim ledge',12);message='You follow the revealed ledge beneath Brindle’s arch and climb the castle hill.';cost=0;}else message='The wall has no visible footholds.';}
else if(h.id==='sella'&&verb==='Talk'){set(s,'errand-told');remember(s,'sella','told-aldus-injured');message=s.flags['key-shown']?'“The Bellkeeper’s key and his errand. Go straight to the tower.”':'“Aldus is injured?” Sella’s expression sharpens. “Show me the Sun Key, and I shall let you through.”';if(s.flags['key-shown']){s.values.arrival=s.minute;arrive(s,'tower','main gate',4);}cost=2;}
else if(h.id==='main-gate'&&verb==='Open'){message=s.minute>=1260?'The ninth bell has sounded. The main gate is barred from inside.':'Sella needs to hear your errand and see the Sun Key before she admits you.';}
else if(h.id==='postern'&&verb==='Open'){message='An old sunburst lock holds the door. This is a courier’s entrance.';}
else if(h.id==='yoke'&&verb==='Turn'){message=s.flags.yoke?'The Sun Key has unlocked the yoke. The release pin is still held by the catch.':'The sunburst yoke requires its key.';}
else if(h.id==='catch'&&verb==='Pull'){if(!s.flags.yoke)message='The locked yoke holds the release pin. It must be unlocked first.';else if(s.minute>=1260&&!s.flags['briar-cleared']&&!s.flags['catch-revealed'])message='Living thorn binds the mechanism. Something must loosen it, or reveal a safe reach to the old catch.';else{set(s,'released');message='The bronze catch moves. The yoke pin slides free and the great bell settles onto its pivot.';cost=2;}}
else if(h.id==='rope'&&verb==='Pull'){if(!s.flags.released)message='The rope strains against a bell that is still held fast. The release mechanism must be worked first.';else if(s.minute>=1290&&!s.flags['rope-repaired']&&!s.flags['rope-spliced']){set(s,'rope-damaged');message='A thorn-cut strand gives way. The remaining sound length reaches a lower cleat; a new knot can join the pull.';}else{finish(s,false);message=s.message;cost=1;}}
else if(h.id==='rope'&&verb==='Tie'){if(s.flags['rope-damaged']){set(s,'rope-spliced');message='Mara splices the sound end around the lower cleat. There is just enough line to ring the bell. Her master would approve of the knot.';cost=5;}else message='The pull is sound; no knot is needed.';}
else message='Mara tests the object’s weight and edges. Nothing moves yet; its physical state has not changed.';
return {message,cost};
}
export function finish(s:State,handover:boolean){s.finished=true;s.flags['bell-rung']=true;s.flags.handover=handover;record(s,'ring','Moon Bell',handover?'The relief courier carries the Sun Key to the tower; together you hear the bell ring.':'Mara rings the Moon Bell.');s.message=handover?'The last runner takes the Sun Key. A little later, the Moon Bell answers across the valley. The road has remembered its promise.':'The Moon Bell rings. Silver sound travels through the valley; living thorn uncurls, and the Briar Road is a road again.';}
export function epilogue(s:State){const lines:string[]=[];const ringing=s.events.find(e=>e.action==='ring'&&e.target==='Moon Bell');lines.push(`Aldus receives his Sun Key again. “A road is kept by those who walk it,” he says. The bell sounded at ${String(Math.floor((ringing?.at||s.minute)/60)).padStart(2,'0')}:${String((ringing?.at||s.minute)%60).padStart(2,'0')}.`);lines.push(s.memories.bram.includes('saw-mara-help-wheel')?'Bram’s wheel turns through the night. By morning, he calls the repaired crossing Mara’s span.':s.values['mill-solution']==='ferry'?'The ferryman remembers an apprentice among the first fireflies. Bram tends his flooded mill.':'Bram finds the sluice shifted and the stones wet with a traveler’s hurried passage.');lines.push(s.memories.ysabet.includes('lantern-returned')?'Ysabet finds her lantern back on its hook, and remembers the hands that returned it.':s.flags.permission?'Ysabet waits for her borrowed lantern, with Mallow safe in the coop.':s.memories.ysabet.includes('saw-lantern-with-mara')?'Ysabet knows whose hands carried her lantern. She expects a knock when Mara comes back.':s.memories.ysabet.includes('lantern-missing')?'Ysabet finds an empty lantern hook. She knows it is missing; she does not know who took it.':'At Ysabet’s cottage, the lantern stays on its hook. A few fireflies find their way home.');lines.push(s.values['bridge-solution']==='bell'?'Brindle rings his little toll bell once, in answer to the great bell. The bridge has its voice again.':s.memories.brindle.includes('saw-key-with-mara')?'Brindle remembers Mara with his brass key and expects it beside his nest.':s.flags['key-taken']?'Brindle finds his key missing after he wakes. He wonders which traveler passed while he slept.':'Brindle hears the Moon Bell above the ravine, unaware of the traveler who used the pilgrim ledge.');lines.push(Number(s.values.arrival||s.minute)<1260?'Sella remembers opening the main gate to Aldus’s young courier before the ninth bell.':'The main gate stayed shut. An old courier door did the work it was built to do.');return lines;}
