(function(){
"use strict";
const SCHEMA=4, KEY="cameraSafetyNotifier.client.v4", RDAP="https://rdap.org/ip/";
let cases=[], selected=null, editingId=null;
const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const yes=v=>["true","1","yes","on"].includes(String(v??"").toLowerCase());
const email=v=>{v=String(v||"").trim();return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v)?v:""};
const makeId=()=>"CAM-"+new Date().getFullYear()+"-"+Math.random().toString(36).slice(2,8).toUpperCase();
const localDT=iso=>{if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const z=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+z(d.getMonth()+1)+"-"+z(d.getDate())+"T"+z(d.getHours())+":"+z(d.getMinutes())};
const isoFromLocal=v=>v?new Date(v).toISOString():now();
function validIp(v){if(!v)return false;if(v.includes(":"))return /^[0-9a-f:]+$/i.test(v)&&v.includes(":");const p=v.split(".");return p.length===4&&p.every(x=>/^\d+$/.test(x)&&+x>=0&&+x<=255)}
function validDomain(v){if(!v)return true;v=v.toLowerCase().trim().replace(/^https?:\/\//,"").split("/")[0];return /^(?!localhost$)(?!.*\.local$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(v)}
function cleanDomain(v){return String(v||"").trim().toLowerCase().replace(/^https?:\/\//,"").split("/")[0]}
function audit(f,action,note=""){f.history=f.history||[];f.history.unshift({at:now(),action,note});f.updated_at=now()}
function normalize(raw){const m={};Object.keys(raw||{}).forEach(k=>m[k.trim().toLowerCase().replace(/[\s-]+/g,"_")]=raw[k]);const p=(...ks)=>{for(const k of ks){const v=m[k];if(v!==undefined&&v!==null&&String(v)!=="")return v}};const f={finding_id:String(p("finding_id","id","case_id")||makeId()),observed_at:String(p("observed_at","timestamp","date")||now()),source:String(p("source","dataset")||""),ip:String(p("ip","ip_address","address")||"").trim(),port:Number(p("port")||0)||null,protocol:String(p("protocol","service")||""),vendor:String(p("vendor","manufacturer")||""),model:String(p("model","product")||""),banner:String(p("banner","metadata","notes")||""),network:String(p("network","organization","owner","isp")||""),owner_type:String(p("owner_type","asset_type")||"unknown").toLowerCase(),domain:cleanDomain(p("domain","organization_domain","website")),security_contact:email(p("security_contact","abuse_contact","security_email","abuse_email","contact")),vendor_contact:email(p("vendor_contact","psirt","vendor_email")),advisory:String(p("advisory","cve","cve_id")||""),known_vulnerability:yes(p("known_vulnerability","known_vuln","vulnerable")),suspected_intrusion:yes(p("suspected_intrusion","intrusion","compromised")),immediate_danger:yes(p("immediate_danger","danger","emergency")),status:String(p("status")||"new").toLowerCase(),approved:yes(p("approved")),contact_verified:yes(p("contact_verified")),contact_note:String(p("contact_note")||""),draft_override:String(p("draft_override")||""),notification_count:Number(p("notification_count")||0)||0,notified_at:p("notified_at")||null,resolved_at:p("resolved_at")||null,created_at:String(p("created_at")||now()),updated_at:String(p("updated_at")||now()),rdap:raw.rdap||null,rechecks:Array.isArray(raw.rechecks)?raw.rechecks:[],history:Array.isArray(raw.history)?raw.history:[]};if(!f.history.length)f.history=[{at:f.created_at,action:"case created",note:f.source||""}];return f}
function triage(f){const text=[f.protocol,f.banner,f.vendor,f.model].join(" ").toLowerCase();let score=0,device="unknown",why=[];const add=(term,w,msg)=>{if(text.includes(term)){score+=w;why.push(msg||`Matched metadata indicator: ${term}.`)}};if(/\bnvr\b|\bdvr\b|network video recorder/.test(text)){device="nvr/dvr";score=.95;why.push("Metadata identifies an NVR/DVR.")}else{add("network camera",.55);add("ip camera",.55);add("onvif",.5,"ONVIF metadata strongly supports a network-video-device classification.");add("camera",.3);add("rtsp",.22);add("webcam",.35);add("surveillance",.25);if(f.port===554){score+=.2;why.push("Port 554 commonly carries RTSP; it supports but does not prove camera identification.")}if(f.port===8554){score+=.14;why.push("Port 8554 commonly carries alternate RTSP.")}score=Math.min(score,.99);if(score>=.6)device="camera";else if(score>=.3)device="possible camera/video device"}
let risk="manual review",route="human review",contact="",contactSource="";
if(f.immediate_danger){risk="escalation review";route="urgent human safety review";why.push("Immediate-danger cases remain human-only; the app never contacts law enforcement automatically.")}
else if(f.suspected_intrusion){risk="escalation review";route="security incident / human review";why.push("Possible intrusion requires evidence-preserving human review, not an automated accusation.")}
else if(f.known_vulnerability){risk="known vulnerability";if(f.vendor_contact){route="vendor PSIRT";contact=f.vendor_contact;contactSource="vendor contact"}else if(f.owner_type==="organization"&&f.security_contact){route="organization security";contact=f.security_contact;contactSource="supplied security contact"}else route="vendor / CERT coordination review";why.push("A known applicable vulnerability raises priority above simple exposure.")}
else if(device!=="unknown"&&score>=.8)risk="probable misconfiguration";else if(score>=.3||f.port)risk="reachable";
if(!contact&&risk!=="escalation review"){if(f.owner_type==="organization"&&f.security_contact){route="organization security";contact=f.security_contact;contactSource="supplied security contact";why.push("Organization-owned asset has a supplied security contact.")}else if(f.owner_type==="residential"&&f.security_contact){route="ISP abuse/security";contact=f.security_contact;contactSource="supplied ISP contact";why.push("Residential cases route through the ISP rather than trying to identify the resident.")}else if(f.owner_type==="network"&&f.security_contact){route="network abuse/security";contact=f.security_contact;contactSource="supplied network contact";why.push("Network case has a supplied security/abuse contact.")}else if(f.rdap&&f.rdap.email){route=f.owner_type==="residential"?"ISP abuse/security":"network abuse/security";contact=f.rdap.email;contactSource="RDAP";why.push("RDAP supplied a network contact; verify it manually before sending.")}else if(route==="human review")why.push("No responsible-party contact is available yet.")}
return{device,confidence:Math.round(score*1000)/10,risk,route,contact,contactSource,why,ready:Boolean(f.approved&&f.contact_verified&&contact&&risk!=="escalation review")}}
function baseDraft(f){const t=triage(f);return `Subject: Possible publicly reachable camera-related service (${f.finding_id})\n\nHello,\n\nOur public-service security project received metadata indicating that a service at ${f.ip||"[IP unavailable]"}${f.port?":"+f.port:""} was publicly reachable at ${f.observed_at}.\n\nThe imported metadata is consistent with a ${t.device} (confidence ${t.confidence}%).${f.known_vulnerability?` A known applicable vulnerability was flagged${f.advisory?` (${f.advisory})`:""}.`:""}\n\nWe did not view video or audio, retrieve snapshots, attempt credentials, bypass authentication, exploit a vulnerability, or send commands to the device. This notification is based on service metadata only.\n\nPlease verify whether the exposure is intended. If not, consider restricting Internet access and reviewing the device/vendor security guidance.\n\nReference: ${f.finding_id}\n\nThank you.`}
function currentDraft(f){return f.draft_override||baseDraft(f)}
function followupDraft(f){const last=f.rechecks&&f.rechecks[0];return `Subject: Follow-up: possible publicly reachable camera-related service (${f.finding_id})\n\nHello,\n\nThis is a follow-up to our earlier notification regarding ${f.ip}${f.port?":"+f.port:""}. ${last&&last.result==="still reachable"?`A later authorized metadata review on ${last.checked_at} still indicated the service was reachable.`:"We are following up on the earlier metadata finding."}\n\nWe have not accessed camera content, attempted credentials, bypassed authentication, exploited the device, or sent commands.\n\nReference: ${f.finding_id}\n\nThank you.`}
function save(){localStorage.setItem(KEY,JSON.stringify({schema:SCHEMA,cases}));$("store").textContent=`Stored locally · ${cases.length} case${cases.length===1?"":"s"}`}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");const raw=Array.isArray(x)?x:(x&&Array.isArray(x.cases)?x.cases:[]);cases=raw.map(normalize)}catch{cases=[]}}
const current=()=>cases.find(x=>x.finding_id===selected);
const riskClass=r=>r==="known vulnerability"||r==="escalation review"?"hi":r==="probable misconfiguration"?"med":"";
function render(){const q=$("q").value.toLowerCase(),rf=$("rf").value,sf=$("sf").value;const arr=cases.filter(f=>{const t=triage(f),hay=[f.finding_id,f.ip,f.vendor,f.model,f.network,f.banner,f.source,t.device,t.route].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!rf||t.risk===rf)&&(!sf||f.status===sf)});$("rows").innerHTML=arr.map(f=>{const t=triage(f);return `<tr data-id="${esc(f.finding_id)}" class="${f.finding_id===selected?"sel":""}"><td><strong>${esc(f.finding_id)}</strong><div class="small">${esc(f.ip)}${f.port?":"+esc(f.port):""}</div></td><td>${esc(t.device)}</td><td>${t.confidence}%</td><td><span class="pill ${riskClass(t.risk)}">${esc(t.risk)}</span></td><td>${esc(t.route)}</td><td>${esc(f.network||f.rdap?.name||"—")}</td><td><span class="pill ${f.status==="resolved"?"ok":""}">${esc(f.status)}</span></td></tr>`}).join("")||'<tr><td colspan="7" class="small">No matching cases.</td></tr>';$("rows").querySelectorAll("tr[data-id]").forEach(tr=>tr.addEventListener("click",()=>{selected=tr.dataset.id;render();detail()}));const ts=cases.map(triage);$("st0").textContent=cases.length;$("st1").textContent=ts.filter(t=>t.device==="camera"||t.device==="nvr/dvr").length;$("st2").textContent=ts.filter(t=>t.route.includes("review")||t.risk==="escalation review").length;$("st3").textContent=ts.filter(t=>t.ready).length;$("st4").textContent=cases.filter(f=>f.status==="resolved").length;$("st5").textContent=cases.reduce((n,f)=>n+(f.notification_count||0),0)}
function setMailLinks(f,t){const links=[$("mail"),$("gmail"),$("outlook")];links.forEach(x=>x.classList.add("hidden"));if(!t.ready)return;const txt=$("draft").value||currentDraft(f),subject=(txt.match(/^Subject:\s*(.*)$/m)||[])[1]||`Security notification (${f.finding_id})`,body=txt.replace(/^Subject:.*\n\n?/m,"");$("mail").href=`mailto:${encodeURIComponent(t.contact)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;$("gmail").href=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(t.contact)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;$("outlook").href=`https://outlook.office.com/mail/deeplink/compose?to=${encodeURIComponent(t.contact)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;links.forEach(x=>x.classList.remove("hidden"))}
function detail(){const f=current();$("empty").classList.toggle("hidden",!!f);$("detail").classList.toggle("hidden",!f);if(!f){$("sid").textContent="None";return}const t=triage(f);$("sid").textContent=f.finding_id;$("dv").textContent=t.device;$("dc").textContent=t.confidence+"%";$("dr").textContent=t.risk;$("dro").textContent=t.route;$("dn").textContent=f.network||f.rdap?.name||"Unknown";$("dco").textContent=t.contact||"Not verified";$("why").innerHTML=t.why.map(x=>`<li>${esc(x)}</li>`).join("");$("meta").textContent=JSON.stringify({finding_id:f.finding_id,observed_at:f.observed_at,source:f.source,ip:f.ip,port:f.port,protocol:f.protocol,vendor:f.vendor,model:f.model,network:f.network,owner_type:f.owner_type,domain:f.domain,banner:f.banner,advisory:f.advisory,known_vulnerability:f.known_vulnerability,suspected_intrusion:f.suspected_intrusion,immediate_danger:f.immediate_danger,status:f.status},null,2);$("draft").value=currentDraft(f);$("gate").className="gate"+(f.approved?" ok":"");$("gate").textContent=f.approved?"Notice approved by a human reviewer.":"Not approved. Review metadata and routing first.";$("approve").textContent=f.approved?"Revoke approval":"Approve notice";$("contactGate").className="gate"+(f.contact_verified?" ok":"");$("contactGate").textContent=f.contact_verified?`Contact verified${f.contact_note?": "+f.contact_note:"."}`:"Contact has not been verified.";$("verifyContact").textContent=f.contact_verified?"Revoke contact verification":"Verify contact";$("rdapo").classList.toggle("hidden",!f.rdap);$("rdapo").textContent=f.rdap?JSON.stringify(f.rdap,null,2):"";$("securityTxt").disabled=!validDomain(f.domain);$("recheckCount").textContent=`${f.rechecks.length} check${f.rechecks.length===1?"":"s"}`;$("rechecks").innerHTML=f.rechecks.map(r=>`<div class="recheck"><strong>${esc(r.result)}</strong><span class="small">${esc(r.checked_at)} · ${esc(r.source||"source not recorded")}</span>${r.notes?`<div class="small">${esc(r.notes)}</div>`:""}</div>`).join("")||'<p class="small">No re-checks recorded.</p>';$("auditCount").textContent=`${f.history.length} event${f.history.length===1?"":"s"}`;$("audit").innerHTML=f.history.slice(0,20).map(h=>`<div class="audit-item"><strong>${esc(h.action)}</strong><span>${esc(h.at)}${h.note?" · "+esc(h.note):""}</span></div>`).join("");setMailLinks(f,t)}
function validateCase(o){const e=[];if(!validIp(o.ip))e.push("Enter a valid IPv4 or IPv6 address.");if(o.port&&(o.port<1||o.port>65535))e.push("Port must be between 1 and 65535.");if(o.domain&&!validDomain(o.domain))e.push("Domain must be a public hostname such as example.org.");return e}
function upsert(list,label="import"){const map=new Map(cases.map(f=>[f.finding_id,f]));let added=0,updated=0,skipped=0;for(const raw of list){const f=normalize(raw);if(validateCase(f).length){skipped++;continue}if(map.has(f.finding_id)){const old=map.get(f.finding_id),preserve={history:old.history,rechecks:old.rechecks,approved:old.approved,contact_verified:old.contact_verified,contact_note:old.contact_note,draft_override:old.draft_override,notification_count:old.notification_count,notified_at:old.notified_at,resolved_at:old.resolved_at,created_at:old.created_at,rdap:old.rdap,status:old.status};Object.assign(old,f,preserve);audit(old,"case updated",label);updated++}else{audit(f,"case imported",label);cases.push(f);map.set(f.finding_id,f);added++}}save();render();if(!selected&&cases[0])selected=cases[0].finding_id;detail();if(skipped)alert(`${skipped} record(s) skipped because the IP/domain/port validation failed.`);return{added,updated,skipped}}
function parseCSV(txt){const rs=[];let r=[],v="",quoted=false;for(let i=0;i<txt.length;i++){const c=txt[i],n=txt[i+1];if(c==='"'&&quoted&&n==='"'){v+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){r.push(v);v=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;r.push(v);v="";if(r.some(x=>x.trim()))rs.push(r);r=[]}else v+=c}r.push(v);if(r.some(x=>x.trim()))rs.push(r);if(rs.length<2)return[];const h=rs[0].map(x=>x.trim());return rs.slice(1).map(row=>Object.fromEntries(h.map((k,i)=>[k,row[i]||""])))}
function download(name,text,type="application/json"){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function csvCell(v){const s=String(v??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function samples(){return[{finding_id:"CAM-DEMO-001",observed_at:"2026-09-23T18:04:00Z",source:"Synthetic fixture",ip:"192.0.2.44",port:554,protocol:"RTSP",vendor:"ExampleCam",model:"EC-100",banner:"RTSP/1.0 Network Camera",network:"Example Residential ISP",owner_type:"residential",security_contact:"abuse@example.org"},{finding_id:"CAM-DEMO-002",observed_at:"2026-09-23T18:08:00Z",source:"Synthetic fixture",ip:"198.51.100.77",port:443,protocol:"HTTPS",vendor:"ExampleVision",banner:"Example NVR management service",network:"Example Library",owner_type:"organization",domain:"example.org",security_contact:"security@example.org"},{finding_id:"CAM-DEMO-003",observed_at:"2026-09-23T18:13:00Z",source:"Synthetic fixture",ip:"203.0.113.22",port:8080,protocol:"HTTP",vendor:"Example Devices",banner:"Embedded device management",network:"Example Network",owner_type:"unknown"},{finding_id:"CAM-DEMO-004",observed_at:"2026-09-23T18:17:00Z",source:"Synthetic fixture",ip:"192.0.2.88",port:554,protocol:"RTSP",vendor:"ExampleSecureCam",banner:"ONVIF RTSP network camera",network:"Example Office",owner_type:"organization",known_vulnerability:true,advisory:"CVE-DEMO-0001",vendor_contact:"psirt@example.org"},{finding_id:"CAM-DEMO-005",observed_at:"2026-09-23T18:21:00Z",source:"Synthetic fixture",ip:"203.0.113.99",port:554,protocol:"RTSP",vendor:"ExampleCam",banner:"Network camera metadata; possible unauthorized changes reported",network:"Example Business",owner_type:"organization",security_contact:"security@example.org",suspected_intrusion:true}]}
function openCaseModal(f=null){editingId=f?.finding_id||null;$("caseTitle").textContent=f?"Edit metadata finding":"Add metadata finding";const form=$("caseForm");form.reset();$("caseError").classList.add("hidden");if(f){for(const [k,v] of Object.entries(f)){const el=form.elements[k];if(!el)continue;if(el.type==="checkbox")el.checked=Boolean(v);else if(k==="observed_at")el.value=localDT(v);else el.value=v??""}}else form.elements.observed_at.value=localDT(now());$("caseModal").classList.add("open")}
function closeModals(){document.querySelectorAll(".modal.open").forEach(m=>m.classList.remove("open"))}
$("samples").addEventListener("click",()=>upsert(samples(),"sample fixtures"));$("add").addEventListener("click",()=>openCaseModal());$("imp").addEventListener("click",()=>$("file").click());$("restore").addEventListener("click",()=>$("restoreFile").click());document.querySelectorAll(".closeModal").forEach(b=>b.addEventListener("click",closeModals));
$("file").addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{const txt=await f.text();let data;if(f.name.toLowerCase().endsWith(".csv"))data=parseCSV(txt);else{const o=JSON.parse(txt);data=Array.isArray(o)?o:(Array.isArray(o.records)?o.records:(Array.isArray(o.cases)?o.cases:[o]))}const r=upsert(data,"file import");alert(`Import complete: ${r.added} added, ${r.updated} updated, ${r.skipped} skipped.`)}catch(err){alert("Import failed: "+err.message)}e.target.value=""});
$("backup").addEventListener("click",()=>download(`camera-safety-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({schema:SCHEMA,exported_at:now(),cases},null,2)));
$("restoreFile").addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{const o=JSON.parse(await f.text());if(!o||!Array.isArray(o.cases))throw new Error("Not a Camera Safety Notifier backup.");if(!confirm(`Replace local project with ${o.cases.length} case(s) from this backup?`))return;cases=o.cases.map(normalize);selected=cases[0]?.finding_id||null;save();render();detail()}catch(err){alert("Restore failed: "+err.message)}e.target.value=""});
$("exportCsv").addEventListener("click",()=>{const h=["finding_id","observed_at","source","ip","port","protocol","vendor","model","network","owner_type","device","confidence","risk","route","status","approved","contact_verified","notification_count","recheck_count"];const rows=cases.map(f=>{const t=triage(f);return[f.finding_id,f.observed_at,f.source,f.ip,f.port||"",f.protocol,f.vendor,f.model,f.network,f.owner_type,t.device,t.confidence,t.risk,t.route,f.status,f.approved,f.contact_verified,f.notification_count,f.rechecks.length]});download("camera-safety-cases.csv",[h,...rows].map(r=>r.map(csvCell).join(",")).join("\n"),"text/csv")});
$("publicReport").addEventListener("click",()=>{const ts=cases.map(triage),report={generated_at:now(),total_cases:cases.length,likely_camera_or_nvr:ts.filter(t=>t.device==="camera"||t.device==="nvr/dvr").length,probable_misconfiguration:ts.filter(t=>t.risk==="probable misconfiguration").length,known_vulnerability:ts.filter(t=>t.risk==="known vulnerability").length,notifications_sent:cases.reduce((n,f)=>n+f.notification_count,0),resolved:cases.filter(f=>f.status==="resolved").length,note:"Aggregate report intentionally excludes IP addresses, contacts, banners, and organization names."};download("camera-safety-public-summary.json",JSON.stringify(report,null,2))});
$("clear").addEventListener("click",()=>{if(confirm("Clear all locally stored cases and audit history?")){cases=[];selected=null;localStorage.removeItem(KEY);save();render();detail()}});$("q").addEventListener("input",render);$("rf").addEventListener("change",render);$("sf").addEventListener("change",render);
$("caseForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.currentTarget),o=Object.fromEntries(fd.entries());["known_vulnerability","suspected_intrusion","immediate_danger"].forEach(k=>o[k]=fd.has(k));o.observed_at=isoFromLocal(o.observed_at);o.domain=cleanDomain(o.domain);o.port=Number(o.port)||null;const errs=validateCase(o);if(errs.length){$("caseError").textContent=errs.join(" ");$("caseError").classList.remove("hidden");return}if(editingId){const f=current();if(!f)return;const protectedFields={history:f.history,rechecks:f.rechecks,approved:f.approved,contact_verified:f.contact_verified,contact_note:f.contact_note,draft_override:f.draft_override,notification_count:f.notification_count,notified_at:f.notified_at,resolved_at:f.resolved_at,created_at:f.created_at,status:f.status,rdap:f.rdap};const n=normalize({...o,finding_id:editingId});Object.assign(f,n,protectedFields);audit(f,"case edited","metadata updated")}else{const n=normalize(o);audit(n,"case created","manual entry");cases.push(n);selected=n.finding_id}save();render();detail();closeModals()});
$("edit").addEventListener("click",()=>{const f=current();if(f)openCaseModal(f)});$("delete").addEventListener("click",()=>{const f=current();if(!f)return;if(confirm(`Delete ${f.finding_id} and its local audit history?`)){cases=cases.filter(x=>x.finding_id!==f.finding_id);selected=cases[0]?.finding_id||null;save();render();detail()}});
$("editContact").addEventListener("click",()=>{const f=current();if(!f)return;const form=$("contactForm");for(const k of ["network","owner_type","domain","security_contact","vendor_contact","contact_note"])form.elements[k].value=f[k]||"";$("contactModal").classList.add("open")});
$("contactForm").addEventListener("submit",e=>{e.preventDefault();const f=current();if(!f)return;const o=Object.fromEntries(new FormData(e.currentTarget).entries());o.domain=cleanDomain(o.domain);if(o.domain&&!validDomain(o.domain)){alert("Enter a public domain such as example.org.");return}Object.assign(f,o,{security_contact:email(o.security_contact),vendor_contact:email(o.vendor_contact),contact_verified:false});audit(f,"contact details updated","verification reset");save();render();detail();closeModals()});
$("verifyContact").addEventListener("click",()=>{const f=current(),t=f&&triage(f);if(!f)return;if(!f.contact_verified&&!t.contact){alert("Add or resolve a responsible security/abuse contact before verifying it.");return}f.contact_verified=!f.contact_verified;audit(f,f.contact_verified?"contact verified":"contact verification revoked",f.contact_note||t.contactSource);save();render();detail()});
$("reviewed").addEventListener("click",()=>{const f=current();if(!f)return;f.status="reviewed";audit(f,"case reviewed");save();render();detail()});$("approve").addEventListener("click",()=>{const f=current();if(!f)return;f.approved=!f.approved;if(f.approved&&["new","reviewed"].includes(f.status))f.status="approved";audit(f,f.approved?"notice approved":"notice approval revoked");save();render();detail()});$("notified").addEventListener("click",()=>{const f=current(),t=f&&triage(f);if(!f)return;if(!t.ready){alert("A notice can be marked sent only after human approval and contact verification, and not for escalation-review cases.");return}f.notification_count++;f.notified_at=now();f.status="notified";f.draft_override=$("draft").value;audit(f,"notification marked sent",`${t.route} → ${t.contact}`);save();render();detail()});$("resolved").addEventListener("click",()=>{const f=current();if(!f)return;f.status="resolved";f.resolved_at=now();audit(f,"case resolved",f.rechecks[0]?.result||"");save();render();detail()});
$("draft").addEventListener("input",()=>{const f=current();if(!f)return;f.draft_override=$("draft").value;save();setMailLinks(f,triage(f))});$("resetDraft").addEventListener("click",()=>{const f=current();if(!f)return;f.draft_override="";audit(f,"draft reset");save();detail()});$("copy").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("draft").value);$("copy").textContent="Copied";setTimeout(()=>$("copy").textContent="Copy draft",1000)}catch{alert("Clipboard access is unavailable. Select the draft and copy it manually.")}});
$("rdap").addEventListener("click",async()=>{const f=current();if(!f?.ip)return;if(!confirm(`Send only ${f.ip} to rdap.org for a public registration lookup?`))return;$("rdap").disabled=true;$("rdapo").classList.remove("hidden");$("rdapo").textContent="Looking up RDAP…";try{const res=await fetch(RDAP+encodeURIComponent(f.ip),{headers:{Accept:"application/rdap+json, application/json"}});if(!res.ok)throw new Error("HTTP "+res.status);const j=await res.json();let em="";(j.entities||[]).forEach(ent=>((ent.vcardArray&&ent.vcardArray[1])||[]).forEach(x=>{if(x[0]==="email"&&!em)em=email(x[3])}));f.rdap={looked_up_at:now(),name:j.name||j.handle||"",handle:j.handle||"",country:j.country||"",startAddress:j.startAddress||"",endAddress:j.endAddress||"",email:em};if(!f.network&&f.rdap.name)f.network=f.rdap.name;if(!f.security_contact&&em)f.security_contact=em;f.contact_verified=false;audit(f,"RDAP lookup completed",f.rdap.name||f.rdap.handle);save();render();detail()}catch(e){f.rdap={looked_up_at:now(),error:String(e.message||e)};audit(f,"RDAP lookup failed",f.rdap.error);save();detail()}finally{$("rdap").disabled=false}});
$("securityTxt").addEventListener("click",()=>{const f=current();if(!f||!validDomain(f.domain))return;window.open(`https://${f.domain}/.well-known/security.txt`,"_blank","noopener");audit(f,"security.txt opened",f.domain);save();detail()});
$("addRecheck").addEventListener("click",()=>{const f=current();if(!f)return;const form=$("recheckForm");form.reset();form.elements.checked_at.value=localDT(now());$("recheckModal").classList.add("open")});$("recheckForm").addEventListener("submit",e=>{e.preventDefault();const f=current();if(!f)return;const o=Object.fromEntries(new FormData(e.currentTarget).entries());const r={checked_at:isoFromLocal(o.checked_at),result:o.result,source:o.source||"",notes:o.notes||""};f.rechecks.unshift(r);if(r.result==="still reachable"&&f.status==="notified")f.status="follow-up due";if(r.result==="still reachable"&&f.notification_count>0&&!f.draft_override)f.draft_override=followupDraft(f);audit(f,"re-check recorded",r.result);save();render();detail();closeModals()});
load();render();detail();
})();