import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync('dist/index.html','utf8'),nodes=new Map(),all=[];
class Element{constructor(id,attrs='',tag='div',content=''){this.id=id;this.tag=tag;this.attrs=attrs;this.value=attrs.match(/value="([^"]*)"/)?.[1]??'';this.checked=/\bchecked\b/.test(attrs);this.innerHTML='';this.textContent='';this.style={};this.listeners={};const cl=new Set((attrs.match(/class="([^"]*)"/)?.[1]??'').split(' '));this.classList={contains:v=>cl.has(v),toggle:(v,b)=>b?cl.add(v):cl.delete(v)};this.labels=[{textContent:id}];this.dataset={};for(const m of attrs.matchAll(/data-(\w+)="([^"]*)"/g))this.dataset[m[1]]=m[2];if(tag==='select'){this.options=[...content.matchAll(/<option value="([^"]*)"([^>]*)>([^<]*)/g)].map(m=>({value:m[1],textContent:m[3],selected:/selected/.test(m[2])}));this.value=(this.options.find(o=>o.selected)??this.options[0])?.value??'';}}get selectedOptions(){return [{textContent:this.options?.find(o=>o.value===this.value)?.textContent??this.value}];}checkValidity(){if(this.tag!=='input')return true;const min=this.attrs.match(/min="([^"]*)"/)?.[1],max=this.attrs.match(/max="([^"]*)"/)?.[1];return Number.isFinite(Number(this.value))&&(min===undefined||Number(this.value)>=Number(min))&&(max===undefined||Number(this.value)<=Number(max));}addEventListener(name,cb){this.listeners[name]=cb;}click(){}}
for(const m of html.matchAll(/<(input|select|div|p|h[123]|table|button|section|details)\b([^>]*\bid="([^"]+)"[^>]*)>([\s\S]*?)(?=<\/\1>|<input)/g)){const el=new Element(m[3],m[2],m[1],m[4]);nodes.set(el.id,el);all.push(el);}
for(const m of html.matchAll(/<select([^>]*id="([^"]+)"[^>]*)>([\s\S]*?)<\/select>/g)){const el=new Element(m[2],m[1],'select',m[3]);nodes.set(el.id,el);all.push(el);}
// Inputs are void elements, so parse them independently.
for(const m of html.matchAll(/<input\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const el=new Element(m[2],m[1],'input');nodes.set(el.id,el);all.push(el);}
for(const m of html.matchAll(/<button([^>]*data-(?:tab|scenario)="[^"]+"[^>]*)>/g))all.push(new Element('',m[1],'button'));
for(const id of [...html.matchAll(/\bid="([^"]*)"/g)].map(m=>m[1]))if(!nodes.has(id)){const el=new Element(id);nodes.set(id,el);all.push(el);}
const tools=new Map();globalThis.document={modelContext:{registerTool:def=>tools.set(def.name,def)},getElementById:id=>{if(!nodes.has(id))throw Error('Missing element '+id);return nodes.get(id);},querySelector:()=>new Element('legend'),querySelectorAll:sel=>sel==='input, select'?all.filter(e=>['input','select'].includes(e.tag)):sel==='.panel'?['simple','explore','advanced','method'].map(id=>nodes.get(id)):sel==='[data-tab]'?all.filter(e=>e.dataset.tab):sel==='[data-scenario]'?all.filter(e=>e.dataset.scenario):[],addEventListener(){},createElement:()=>new Element('a')};
for(const id of ['simple','explore','advanced','method']){const e=nodes.get(id),cl=new Set(['panel',...(id==='simple'?['active']:[])]);e.classList={contains:v=>cl.has(v),toggle:(v,b)=>b?cl.add(v):cl.delete(v)};}
globalThis.window={addEventListener(){}};globalThis.requestAnimationFrame=cb=>setTimeout(cb,0);globalThis.fetch=async()=>({json:async()=>JSON.parse(fs.readFileSync('dist/history.json'))});
nodes.get('portfolio').value='sp';await import('./dist/app.mjs');assert.equal(nodes.get('error').textContent,'');assert.ok(nodes.get('hero').innerHTML.includes('Investing'));assert.ok(nodes.get('strategyTable').innerHTML.includes('50 / 50'));assert.equal(tools.size,2);const read=tools.get('read_mortgage_invest_analysis').execute({});assert.equal(read.inputs.balance,340000);
await tools.get('configure_and_compare_mortgage_invest').execute({balance:280000,rate:6.5,extra:800,horizon:10});assert.equal(tools.get('read_mortgage_invest_analysis').execute({}).inputs.rate,.065);
const before=nodes.get('balance').value;await assert.rejects(tools.get('configure_and_compare_mortgage_invest').execute({balance:-5}));assert.equal(nodes.get('balance').value,before);
nodes.get('splitButton').onclick();assert.ok(nodes.get('customResult').innerHTML.includes('40% mortgage'));all.find(e=>e.dataset.tab==='explore').onclick();assert.ok(nodes.get('lineChart').innerHTML.includes('<svg'));nodes.get('chartType').value='liquid';nodes.get('chartType').onchange();assert.ok(nodes.get('lineTitle').textContent.includes('Accessible'));nodes.get('reportButton').onclick();console.log('DOM smoke: initial results, calculator updates, invalid inputs, custom allocation, chart switching and report export passed. WebMCP execution checked with a registry stub; supported browser-context validation unavailable.');
