import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import Scene from './render/Scene';
import {useGame,dispatch,save,reload,reset,saveStatus} from './simulation/store';
import {visibleHotspots,timeLabel} from './simulation/game';
import {locations,itemNames,itemDescriptions,type Hotspot} from './content/world';
import {epilogue} from './simulation/puzzles';
import './ui/style.css';
function App(){const s=useGame();const [focus,setFocus]=useState<Hotspot|null>(null);const [tray,setTray]=useState(false);const [journal,setJournal]=useState(false);const [menu,setMenu]=useState(false);const [ending,setEnding]=useState(false);const [waiting,setWaiting]=useState(false);const [selected,setSelected]=useState<string|undefined>();const [reveal,setReveal]=useState(false);
const object=(h:Hotspot)=>{if(h.exit){dispatch({type:'travel',to:h.exit});setFocus(null);}else if(selected){dispatch({type:'interact',id:h.id,verb:'Use',item:selected});setSelected(undefined);setFocus(h);}else{dispatch({type:'interact',id:h.id,verb:'Look'});setFocus(h);}};
return <main onKeyDown={e=>{if(e.key==='Escape'){setFocus(null);setTray(false);setJournal(false);setMenu(false);setWaiting(false);setEnding(false);setSelected(undefined);}if(e.key.toLowerCase()==='i')setTray(v=>!v);if(e.key.toLowerCase()==='h')setReveal(v=>!v);}}><header><span className="chapter">THE SHORTCUT <i>✦</i> THE MOON BELL</span><span>{timeLabel(s)}</span></header><div className="scene-name"><h1>{locations[s.location].name}</h1><p>{locations[s.location].subtitle}</p></div><Scene s={s} reveal={reveal} onObject={object} onWalk={point=>{setFocus(null);dispatch({type:'move',point});}}/>
<div className="narration" aria-live="polite">{selected?`Use ${itemNames[selected]} with…`:s.message}</div>
{focus&&visibleHotspots(s).some(h=>h.id===focus.id)&&<section className="context" aria-label={focus.name}><strong>{focus.name}</strong><div>{(focus.verbs||[]).filter(v=>v!=='Look').map(v=><button key={v} onClick={()=>dispatch({type:'interact',id:focus.id,verb:v})}>{v}</button>)}<button onClick={()=>setFocus(null)}>Close</button></div></section>}
{s.finished?<nav className="tools"><button onClick={()=>setEnding(true)}>Remember the road</button></nav>:<nav className="tools" aria-label="Adventure tools"><button onClick={()=>setTray(v=>!v)}>Satchel <small>I</small></button><button onClick={()=>setJournal(v=>!v)}>Journal</button><button onClick={()=>{setWaiting(v=>!v);setFocus(null);}}>Wait</button><button onClick={()=>setReveal(v=>!v)} aria-pressed={reveal}>Look around <small>H</small></button><button onClick={()=>setMenu(v=>!v)}>Menu</button></nav>}
{waiting&&<section className="drawer"><h2>Let the road breathe</h2><p>You can watch the changing light for a little while.</p>{[1,5,15,30].map(minutes=><button key={minutes} onClick={()=>dispatch({type:'wait',minutes})}>Wait {minutes} {minutes===1?'minute':'minutes'}</button>)}<button onClick={()=>setWaiting(false)}>Continue walking</button></section>}
{ending&&<section className="drawer epilogue"><h2>A road remembered</h2>{epilogue(s).map((line,i)=><p key={i}>{line}</p>)}<details><summary>Your path</summary>{s.events.filter(e=>e.actor==='Mara'&&e.action!=='Look').map((e,i)=><p key={i}>{Math.floor(e.at/60)}:{String(e.at%60).padStart(2,'0')} · {e.result}</p>)}</details><button onClick={()=>setEnding(false)}>Return to the valley</button></section>}
{tray&&<section className="drawer" aria-label="Inventory"><h2>Mara’s satchel</h2><div className="items">{s.inventory.map(i=><button key={i} title={itemDescriptions[i]} aria-pressed={selected===i} onClick={()=>{setSelected(i);setTray(false);}}>✧<span>{itemNames[i]}</span></button>)}</div><p>Select an object, then a place or person. Escape cancels.</p><button onClick={()=>setTray(false)}>Close</button></section>}
{journal&&<section className="drawer"><h2>A locksmith’s notes</h2><p>Carry the Sun Key to Castle Arden before the ninth evening bell.</p>{s.clues.map(c=><p key={c}>{c}</p>)}<button onClick={()=>dispatch({type:'hint'})}>A thought, please</button><button onClick={()=>setJournal(false)}>Close</button></section>}
{menu&&<section className="drawer"><h2>The Moon Bell</h2><p>Click the ground to walk. Click a visible object to look; choose a physical action or use an object from your satchel. Tab and Enter work on the same objects. Reading never advances time.</p><button onClick={save}>Save</button><button onClick={()=>{reload();setFocus(null);}}>Restore</button><button onClick={()=>{if(confirm('Begin a fresh adventure?')){reset();setFocus(null);setMenu(false);}}}>New adventure</button><p>{saveStatus()}</p><button onClick={()=>setMenu(false)}>Close</button></section>}
</main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
